name: Build docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v16.12.0
        uses: actions/setup-node@v1
        with:
          node-version: v16.12.0

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "$NAME"
          git add docs
          git commit -m "Build of the docs/ via GitHub Action"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
